
planka:
  fullnameOverride: planka

  baseUrl: http://planka.intra.soernet.ca

  image:
    tag: 1.26.3

  # Don't use the bundled postgresql
  postgresql:
    enabled: false

  # Use these values if credentialsFromESO is enabled
  existingSecretkeySecret: planka-credentials
  existingAdminCredsSecret: planka-credentials

  # Use this value if you are using the cnpgDatabase option below
  existingDburlSecret: planka-cluster-app

  
credentialsFromESO:
  enabled: true
  secretStoreRef:
    name: aws-use1-parameter-store-cluster-secret-store
    kind: ClusterSecretStore
  keyRemoteRefKey: /k3s-homelab/planka/credentials/key
  adminUsernameRemoteRefKey: /k3s-homelab/planka/credentials/admin_username
  adminPasswordRemoteRefKey: /k3s-homelab/planka/credentials/admin_password


cnpgDatabase:
  enabled: true
  storageClass: synology-nas-csi-iscsi-retain
  size: 10Gi
  instances: 1

traefik:
  ingressRoute:
    enabled: true
    domain: planka.intra.soernet.ca