apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gogs.fullname" . }}
  labels:
    {{- include "gogs.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "gogs.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gogs.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gogs.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      initContainers:
        - name: init-config
          image: dibi/envsubst:1
          # We use 'sh' to replace variables in the template
          command: ['sh', '-c', 'envsubst < /tmp/template/app.ini.template > /tmp/actual/app.ini']
          env:
            # Secrets from the Postgres Operator
            - name: 'DB_HOST'
              valueFrom:
                secretKeyRef:
                  name: gogs-cluster-app
                  key: host
            - name: 'DB_NAME'
              valueFrom:
                secretKeyRef:
                  name: gogs-cluster-app
                  key: dbname
            - name: 'DB_PASSWORD'
              valueFrom:
                secretKeyRef:
                  name: gogs-cluster-app
                  key: password
            - name: 'DB_USER'
              valueFrom:
                secretKeyRef:
                  name: gogs-cluster-app
                  key: username
            # Static secrets defined in your Helm values
            - name: GOGS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-key
                  key: secretKey
          volumeMounts:
            - name: config-template
              mountPath: /tmp/template
            - name: actual-config
              mountPath: /tmp/actual
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "gogs/gogs:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
            - name: ssh
              containerPort: 22

          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            # If persistence is enabled, mount the PVC to /data
            {{- if .Values.persistence.enabled }}
            - name: gogs-persistent-storage
              mountPath: /data
            {{- end }}
            - name: actual-config
              mountPath: /data/gogs/conf/app.ini
              subPath: app.ini
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name : SOCAT_LINK
              value: "false"
      volumes:
        # If persistence is enabled and no existing claim is specified, create a new PVC
        {{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
        - name: gogs-persistent-storage
          persistentVolumeClaim:
            claimName: {{ template "gogs.fullname" . }}-pvc
        {{- end }}
        # If persistence is enabled and an existing claim is specified, use it
        {{- if and .Values.persistence.enabled .Values.persistence.existingClaim }}
        - name: gogs-persistent-storage
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
        {{- end }}
        - name: config-template
          configMap:
            name: {{ include "gogs.fullname" . }}-ini-template
        - name: actual-config
          emptyDir: {}
        # If there are any additional volumes to mount
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
