apiVersion: v1
kind: Service
metadata:
  name: {{ include "gogs.fullname" . }}
  labels:
    {{- include "gogs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
    - port: {{ .Values.service.sshPort }}
      targetPort: 2222
      protocol: TCP
      name: ssh
  selector:
    {{- include "gogs.selectorLabels" . | nindent 4 }}
