{{- if not .Values.configEnvFromSecret.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "price-buddy.fullname" . }}-env-config
data:
  .env: |
    CACHE_STORE=file
    APP_KEY=
{{- end }}