{{- if not ( or .Values.configEnvFromSecret.enabled .Values.configEnvFromESO.enabled ) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "price-buddy.fullname" . }}-env-config
data:
  .env: |
    CACHE_STORE=file
    APP_KEY=
    {{- if .Values.traefik.enabled }}
    APP_URL=https://{{ .Values.traefik.ingressRoute.domain }}
    ASSET_URL=https://{{ .Values.traefik.ingressRoute.domain }}
    {{- end }}
{{- end }}